name: PHP CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [ '8.0', '8.1' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php-versions }}

      - name: Run tests
        uses: php-actions/phpunit@v3
        with:
          version: 9.5
          php_version: ${{ matrix.php-versions }}
          configuration: phpunit.xml
