name: PHP Ci

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [ '7.4', '8.0', '8.1' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit:7.5.5

      - name: Install dependencies
        uses: php-actions/composer@v5

      - name: Run tests
        uses: php-actions/phpunit@v3s
